/**
 * Question → Answer memory.
 *
 * Some dropdowns are not profile *attributes* (country, gender, degree) — they
 * are *questions* whose answer depends on the question itself:
 *   "Do you now or will you need sponsorship…?"            → No
 *   "Are you legally authorized to work in the country…?"  → Yes
 *   "Have you previously worked for Databricks?"           → Yes - Previous Intern
 *
 * These can't be stored under a canonical profile key. Instead we remember the
 * exact answer the user picked, keyed by the question text, and replay it the
 * next time the same question appears — on this site or any other. No AI
 * needed: it's a literal "you answered X to question Q last time" memory.
 *
 * Stored in chrome.storage.local (persists across sessions). Reusable across
 * sites because the key is the question text, not a domain.
 *
 * Each entry carries a `source` tag:
 *   - 'user'  — the user manually typed/clicked this answer. Never auto-invalidated.
 *   - 'llm'   — generated by Gemini via ANSWER_FIELD. Cleared when resume or
 *               profile changes so stale AI guesses don't persist.
 *
 * Backward compat: entries written before this format change are plain strings.
 * On read, they're treated as source:'user' (safe — they predate the LLM tier).
 */

import { STORAGE_KEYS } from '@shared/types';

const KEY = STORAGE_KEYS.QA_CACHE;

export type QASource = 'user' | 'llm';

interface QAEntry {
  answer: string;
  source: QASource;
}

export interface QAAnswer {
  value:    string;
  source:   QASource;
  priority: number;
}

interface QAMultiEntry {
  answers: QAAnswer[];
}

type QAMap = Record<string, string | QAEntry | QAMultiEntry>;

const QA_MAX_ANSWERS = 5;

/** Normalize a question to a stable key: lowercase, collapse whitespace,
 *  strip trailing required-markers / punctuation. */
export function normalizeQuestion(question: string): string {
  return question
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .replace(/[\s*:?.]+$/g, '')
    .trim()
    .slice(0, 240);
}

function isMulti(raw: unknown): raw is QAMultiEntry {
  return typeof raw === 'object' && raw !== null && 'answers' in raw && Array.isArray((raw as QAMultiEntry).answers);
}

function readAllAnswers(raw: string | QAEntry | QAMultiEntry | undefined): QAAnswer[] {
  if (!raw) return [];
  if (typeof raw === 'string') return [{ value: raw, source: 'user', priority: 0 }];
  if (isMulti(raw)) return [...raw.answers].sort((a, b) => a.priority - b.priority);
  if (typeof raw === 'object' && 'answer' in raw && raw.answer) {
    return [{ value: raw.answer, source: (raw as QAEntry).source ?? 'user', priority: 0 }];
  }
  return [];
}

function readEntry(raw: string | QAEntry | QAMultiEntry | undefined): { answer: string; source: QASource } | null {
  const all = readAllAnswers(raw);
  if (all.length === 0) return null;
  return { answer: all[0].value, source: all[0].source };
}

/** Look up the answer the user previously gave to this question. */
export async function getRememberedAnswer(question: string): Promise<string | null> {
  const nq = normalizeQuestion(question);
  if (nq.length < 6) return null;
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = stored[KEY] as QAMap | undefined;
    const entry = readEntry(map?.[nq]);
    return entry?.answer ?? null;
  } catch {
    return null;
  }
}

/** Remember the answer for this question with a source tag.
 *  Adds as a new alternative if a different answer already exists (up to cap). */
export async function rememberAnswer(
  question: string,
  answer: string,
  source: QASource = 'user'
): Promise<void> {
  const nq = normalizeQuestion(question);
  const a = answer.trim();
  if (nq.length < 6 || !a || a.length > 500) return;
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = (stored[KEY] as QAMap | undefined) ?? {};
    const existing = readAllAnswers(map[nq]);

    const normA = a.toLowerCase();
    if (existing.some(e => e.value.toLowerCase() === normA)) return;

    if (existing.length === 0) {
      map[nq] = { answers: [{ value: a, source, priority: 0 }] };
    } else if (existing.length < QA_MAX_ANSWERS) {
      const nextP = Math.max(...existing.map(e => e.priority)) + 1;
      existing.push({ value: a, source, priority: nextP });
      map[nq] = { answers: existing };
    } else {
      // Cap reached — update the default
      existing[0] = { value: a, source, priority: 0 };
      map[nq] = { answers: existing };
    }
    await chrome.storage.local.set({ [KEY]: map });
  } catch {
    /* storage unavailable — non-fatal */
  }
}

/**
 * Purge all LLM-sourced entries from the cache. Called when resume or profile
 * changes — the AI's answers may be stale and need re-generation.
 * User-entered answers (source:'user') are never touched.
 */
export async function clearLlmAnswers(): Promise<void> {
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = (stored[KEY] as QAMap | undefined) ?? {};
    let changed = false;
    for (const key of Object.keys(map)) {
      const all = readAllAnswers(map[key]);
      const userOnly = all.filter(a => a.source !== 'llm');
      if (userOnly.length < all.length) {
        changed = true;
        if (userOnly.length === 0) {
          delete map[key];
        } else {
          map[key] = { answers: userOnly };
        }
      }
    }
    if (changed) await chrome.storage.local.set({ [KEY]: map });
  } catch {
    /* non-fatal */
  }
}

/** Get all stored answers for a question (sorted by priority). */
export async function getRememberedAnswers(question: string): Promise<QAAnswer[]> {
  const nq = normalizeQuestion(question);
  if (nq.length < 6) return [];
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = stored[KEY] as QAMap | undefined;
    return readAllAnswers(map?.[nq]).filter(a => a.source !== 'llm' || a.priority === 0);
  } catch {
    return [];
  }
}

/** Read all entries (for the popup Answers review screen). */
export async function getAllQAEntries(): Promise<Array<{ question: string; answer: string; source: QASource; alternativeCount: number }>> {
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = (stored[KEY] as QAMap | undefined) ?? {};
    const result: Array<{ question: string; answer: string; source: QASource; alternativeCount: number }> = [];
    for (const [q, raw] of Object.entries(map)) {
      const all = readAllAnswers(raw);
      if (all.length > 0) {
        result.push({
          question: q,
          answer: all[0].value,
          source: all[0].source,
          alternativeCount: all.length,
        });
      }
    }
    return result;
  } catch {
    return [];
  }
}

/** Delete a single entry by normalized question key (for the popup). */
export async function deleteQAEntry(normalizedQuestion: string): Promise<void> {
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = (stored[KEY] as QAMap | undefined) ?? {};
    if (!(normalizedQuestion in map)) return;
    delete map[normalizedQuestion];
    await chrome.storage.local.set({ [KEY]: map });
  } catch {
    /* non-fatal */
  }
}

/** Update a single entry's answer and mark it as user-confirmed. */
export async function updateQAEntry(normalizedQuestion: string, newAnswer: string): Promise<void> {
  const a = newAnswer.trim();
  if (!a) {
    await deleteQAEntry(normalizedQuestion);
    return;
  }
  try {
    const stored = await chrome.storage.local.get(KEY);
    const map = (stored[KEY] as QAMap | undefined) ?? {};
    map[normalizedQuestion] = { answer: a, source: 'user' };
    await chrome.storage.local.set({ [KEY]: map });
  } catch {
    /* non-fatal */
  }
}
